/*
 * JMLogWin.java
 *
 * Created on 21 Август 2006 г., 12:23
 */

package captain.northern;

import javax.swing.JTextArea;

/**
 *
 * @author  leo
 */
public class JMLogWin extends javax.swing.JFrame
{
    
    /** Creates new form JMLogWin */
    public JMLogWin()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        closeBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbgTextArea = new javax.swing.JTextArea();
        errOnlyCheck = new javax.swing.JCheckBox();

        setTitle("JMAG: Debug output window");
        closeBut.setText("Close window");
        closeBut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButActionPerformed(evt);
            }
        });

        dbgTextArea.setColumns(20);
        dbgTextArea.setEditable(false);
        dbgTextArea.setRows(5);
        jScrollPane1.setViewportView(dbgTextArea);

        errOnlyCheck.setText("Show error messages only");
        errOnlyCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        errOnlyCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(errOnlyCheck)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 403, Short.MAX_VALUE)
                        .add(closeBut))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(closeBut)
                    .add(errOnlyCheck))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButActionPerformed
    {//GEN-HEADEREND:event_closeButActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButActionPerformed
    
    
    public JTextArea getLogOut() { return dbgTextArea;};
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBut;
    private javax.swing.JTextArea dbgTextArea;
    private javax.swing.JCheckBox errOnlyCheck;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
